baseurl = "https://justseomnotestoread.netlify.app/"
title = "Security+"
author = "Kaz"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "How to lose weight.(with science)"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "This will go to a calorie calculator Soon"
    url  = "http://149.28.35.61:1717/"
[[menu.main]]
    name = "Send me an email."
    url  = "#"

