baseurl = "https://justseomnotestoread.netlify.app/"
title = "Papaya Blog"
author = "Kaz"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Papaya Blog"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://justseomnotestoread.netlify.app/"
[[main.menu]]
    name = "Find me Twitter"
    url = "#"
[[menu.main]]
    name = "Papaya.moe"
    url  = "http://papaya.moe"
[[menu.main]]
    name = "Send me an email."
    url  = "#"

